### ISSUE TITLE
Won't work on my local server

### ISSUE THREAD

**Issue by tyeeman** [MaxLaumeister/PageCrypt#10]
I'm trying to get this working locally being served by my Laragon server. Loading the file works fine, but submit does nothing. Tried saving the web page 2 different ways. Any tips?

**Comment by MaxLaumeister** [comment]
Anything in the JavaScript console?

**Comment by tyeeman** [comment]
I opened Web Developer tools and got this error when I hit submit - 
```
TypeError: templateHTML is undefined
```
I'm not a coder but where can I find the Javascript console in firefox?

**Comment by MaxLaumeister** [comment]
There's a few things that could be at play here, off the top of my head:

PageCrypt loads the template html file by using an ajax request [on line 260](https://github.com/MaxLaumeister/PageCrypt/blob/70292fff4b997352d8552a25d5e5c2a954ca1c0a/index.html#L260). It makes sure the request was successful (status code 200) before enabling the file select box so that the user can start using the app. So it's possible that PageCrypt is requesting `decryptTemplate.html` but Laragon is returning something else with the 200 status code. You do have the `decryptTemplate.html` file in the same folder as the PageCrypt `index.html`, right?

Secondly, PageCrypt uses curly braces [on line 226](https://github.com/MaxLaumeister/PageCrypt/blob/70292fff4b997352d8552a25d5e5c2a954ca1c0a/index.html#L226), which might trip up a templating engine, if that's part of Laragon. Do a "view source" in Firefox and look at line 226, and make sure the server has left the curly braces intact and unaltered.

Thirdly, if you have "pretty urls" enabled, it could be that the server is serving up the `index.html` file in a different "directory" than the `decryptTemplate.html` file. Like, maybe Laragon is serving the app at `/example/pagecrypt/` and the template at `/example/decryptTemplate/`, which won't work because the app looks for the template in the same directory, with the specific name `decryptTemplate.html`.

Those are the things I'd look for!

**Comment by tyeeman** [comment]
These are the only files I have after saving the page - 

github.svg
aes.js
FileSaver.js
pbkdf2.js

decryptTemplate.html is not saved. How do I get it?

**Comment by MaxLaumeister** [comment]
Websites often include JavaScript, which could theoretically load any resource at any time during the page lifecycle for any reason. So just due to the way JavaScript works, if a page uses JS to make ajax requests like PageCrypt and many other sites do, it would be impossible to write an app that could save all required files to exactly simulate that page.

You'll notice that in general, many web pages will not be saved *perfectly* by doing a save-as in the web browser. As a rule of thumb, the less like a web *page* and the more like a web *app* it is, the poorer job a browser will do in saving all the required resources.

I'm glad it's working for you now. Downloading the code from the repo was definitely the fix for that.
