### ISSUE TITLE
Suggestion: use un-minified sources in the demo page

### ISSUE THREAD

**Issue by MKorostoff** [MaxLaumeister/PageCrypt#24]
First of all, awesome project. Such a clever, elegant solution to such a common problem. I have one suggestion. In the [demopage](https://github.com/MaxLaumeister/PageCrypt/blob/master/demopage/index.html), a minified version of CryptoJS is included. This makes it kind of difficult to set breakpoints and learn about the underlying cryptographic methods being applied here. For instance, I spent some time this evening trying to work out "how does it know to raise an error when the wrong password is entered?" (answer: because cryptojs percent encodes all content before encrypting it, and raises an error if the decrypted string cannot be percent decoded).

Since the demo page is all about helping people to learn this tool, I'd like to suggest using an un-minified version of this library to allow easier inspection and deeper learning. It could live is a separate file if you are worried about polluting your main code base with such a large library. I believe this would be the needed file https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/core.js

**Comment by MaxLaumeister** [comment]
Hi Matt,

Thanks for the suggestion. I don't know if this is helpful or is the exact opposite of what you wanted and makes the situation worse, but I just [started a branch](https://github.com/MaxLaumeister/PageCrypt/tree/webcrypto) to remove CryptoJS. I've been a bit lazy and hadn't gotten around to it yet, but the library is outdated now that the Web Crypto API is well-supported in browsers.

This should make the resulting pages lighter, faster, and more secure, as they no longer have to include and execute CryptoJS, and can perform additional rounds of PBKDF2 due to the speed of native execution. However it will also push some of the crypto functions deeper into the browser's native code, making them less step-through-able.

I am a huge fan of your visualizations, by the way!

**Comment by MKorostoff** [comment]
Thanks, makes sense, closing this out since it will be moot/not achievable with the upcoming version.
