### ISSUE TITLE
python implementation is not working

### ISSUE THREAD

**Issue by kmsaumcis** [MaxLaumeister/PageCrypt#26]
The Python implementation is badly out of sync with the JS implementation.

The fix has been submitted in PR25:
https://github.com/MaxLaumeister/PageCrypt/pull/25

**Comment by brenthuisman** [comment]
The Python script (the linked PR has in the meantime been merged) does not seem to produce decryptable files: whether I pass the key as argument or to the prompt, I can never decrypt the page with it. The script does not output any errors. Any idea what's up?

**Comment by kmsaumcis** [comment]
Are you able to verify the versions of the requisite python libraries (they have been updated)?

**Comment by MaxLaumeister** [comment]
My bad. When fixing the Powershell script to use the legacy template, I mistakenly changed the Python script to use it too. Bug introduced in 4a49116fc80482dca02aec3be2e379245a54f86a, fixed in 17619bb8a87342aee5ba41017f54a0fbe1d925a4.

@kmsaumcis Thank you again for the PR, and thanks for helping troubleshoot here.

@brenthuisman If you could confirm that the python script works for you now, that would be helpful. Thanks!

**Comment by brenthuisman** [comment]
I can confirm it works now. Thanks!
