### ISSUE TITLE
Doesnt work with 000webhost?

### ISSUE THREAD

**Issue by noah-kl** [MaxLaumeister/PageCrypt#33]
Works in atom and local but when I upload it to 000webhost nothing happens when I press submit. I think this has to do with 000webhost but I make issue just in case

**Comment by MaxLaumeister** [comment]
If you open up the javascript console before clicking submit, does any error show up in the console?

**Comment by noah-kl** [comment]
Yes, it shows this error
`Uncaught SyntaxError: missing ) after argument list`

**Comment by MaxLaumeister** [comment]
That's a parse-time error, which means that a section of the javascript code got mangled and wasn't able to run.

I believe it's very likely that 000webhost interfered with the PageCrypt code by post-processing the page in some way. Because PageCrypt encrypts entire pages at once, it can be a bit fragile if hosts try to inject extra stuff into it.

So I think your intuition was correct in implicating the host.
