### ISSUE TITLE
Possible to have username and password?

### ISSUE THREAD

**Issue by glitcher32** [MaxLaumeister/PageCrypt#7]
Just curious, that would be an awesome feature.

**Comment by MaxLaumeister** [comment]
Hey @glitcher32, sorry I didn't get around to replying to this.

Having both a username and password presumes multiple sets of credentials, and multiple sets of credentials wouldn't give the application extra usefulness. Because the page is unlocked entirely within the browser (client-side), those credentials never touch the server, so there's no real concept of a user, and no way you could tell who is "logging in".

So, the decision to implement a username field would be strictly a visual/personalization preference rather than a feature. It would add complexity to the app with no material security gain, which is why I would argue against including it.

Thank you for asking about this, though. You didn't deserve to be forgotten for six months - I'll try to be better about replying to issues!
